# Generated by Django 2.0.5 on 2019-04-14 13:02

from django.db import migrations, transaction
from django.contrib.auth.hashers import make_password


def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.username = 'admin'
    superuser.email = 'admin@admin.com'
    password = make_password('admin')
    superuser.password = password
    superuser.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_superuser),
    ]
