# Generated by Django 2.0.5 on 2019-04-23 13:32

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('douban_group_spy', '0001_create_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False, unique=True)),
                ('group_name', models.CharField(max_length=32)),
                ('alt', models.CharField(max_length=128)),
                ('member_count', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=24, unique=True)),
                ('author_info', jsonfield.fields.JSONField(default={})),
                ('alt', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('photo_list', jsonfield.fields.JSONField(default=[])),
                ('rent', models.FloatField(null=True)),
                ('subway', models.CharField(max_length=12, null=True)),
                ('contact', models.CharField(max_length=68, null=True)),
                ('is_matched', models.BooleanField(default=False)),
                ('keyword_list', jsonfield.fields.JSONField(default=[])),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='douban_group_spy.Group')),
            ],
            options={
                'db_table': 'Post',
            },
        ),
    ]
