# Generated by Django 2.0.5 on 2019-04-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban_group_spy', '0002_group_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
