# Generated by Django 2.0.5 on 2019-04-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban_group_spy', '0003_auto_20190424_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
    ]
